# secret Kubernetes pour stocker les informations sensibles pour l'application WordPress
apiVersion: v1
data:
  wordpress_db_password: dG90bwo=                # mot de passe de la base de données WordPress encodé en base64
  mysql_password: dG90bwo=                      # mot de passe MySQL encodé en base64
  mysql_random_root_password: MQo=              # mot de passe aléatoire pour l'utilisateur root MySQL encodé en base64
kind: Secret
metadata:
  name: app-wordpress-secret                    # nom du secret
  namespace: wordpress                          # espace de noms Kubernetes
type: Opaque                                     
