#manifest pour créer un service nodeport pour exposer l'application à l'extérieur du cluster
apiVersion: v1                           # version de l'API Kubernetes utilisée dans ce manifest
kind: Service                            # type de ressource Kubernetes que nous voulons créer (dans ce cas, un service)
metadata:                                # métadonnées pour cette ressource (dans ce cas, le service)
  name: wordpress                       # nom du service que nous voulons créer
  labels:                                # étiquettes qui peuvent être utilisées pour rechercher ce service
    app: wordpress
  namespace: wordpress                   # espace de noms Kubernetes dans lequel nous créons ce service
spec:                                    # spécifications pour ce service
  type: NodePort                         # type de service Kubernetes (dans ce cas, NodePort)
  selector:                              # sélecteur qui sera utilisé pour trouver les pods pour ce service
    app: wordpress
    tier: frontend
  ports:                                 # ports exposés par ce service
    - protocol: TCP                      # protocole de transport utilisé pour les données
      port: 80                           # port exposé par le service
      targetPort: 80                     # port cible sur les pods associés à ce service
      nodePort: 30008                    # port utilisé sur les nœuds pour accéder au service de l'extérieur du cluster
